# configs/paths/default.yaml

# 1. 根目录 (自动获取)
root_dir: ${oc.env:PROJECT_ROOT}

# 2. 数据目录 (通常在项目下，或者你可以指向 GPFS)
data_dir: ${root_dir}/data

# 3. 日志总目录
log_dir: ${root_dir}/logs

# 4. 【核心】本次运行的输出目录
# 这个变量非常神奇，它会自动指向 Hydra 创建的那个带日期的文件夹
# 例如: logs/ae_stage1/runs/2025-12-07_15-00-00
output_dir: ${hydra:runtime.output_dir}

# 5. 工作目录
work_dir: ${hydra:runtime.cwd}