_target_: src.models.components.ae.vanilla.VanillaAE

input_dim: 28231  # 根据实际基因数量调整
hidden_dims: [8192,4096,2048,1024,512]
latent_dim: 512
dropout_rate: 0.1
use_batch_norm: True
activation: "ReLU" # LeakyReLU, GELU, SiLU, ReLU
