# @package _global_

defaults:
  - _self_
  - data: sc_atlas_ae
  - model: ae_stage1
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - extra: default
  - hydra: default
  - experiment: null
task_name: "ae_stage1"
train: True
test: False
seed: 42
ckpt_path: null